<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cuizhi</groupId>
        <artifactId>CuiZhi-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../CuiZhi-parent</relativePath>
    </parent>
    <artifactId>CuiZhi-learning</artifactId>
    <name>CuiZhi-learning</name>
    <description>CuiZhi-learning</description>
    <packaging>pom</packaging>

    <modules>
        <module>CuiZhi-learning-controller</module>
        <module>CuiZhi-learning-model</module>
        <module>CuiZhi-learning-service</module>
    </modules>

</project>
