<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cuizhi</groupId>
        <artifactId>CuiZhi-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>CuiZhi-resource</artifactId>
    <name>CuiZhi-resource</name>
    <packaging>pom</packaging>

    <modules>
        <module>CuiZhi-resource-controller</module>
        <module>CuiZhi-resource-model</module>
        <module>CuiZhi-resource-service</module>
    </modules>

</project>
