-- =====================================================
-- QuenchMind 数据库初始化脚本（PostgreSQL + pgvector）
-- 说明：
-- 1) 本脚本用于“初始化/重建环境”，建议在空库执行。
-- 2) 使用 pgvector 存储向量，默认 1536 维（可按模型调整）。
-- 3) 统一使用 timestamptz，避免时区问题。
-- =====================================================

-- pgvector 扩展（向量类型 + HNSW/IVFFlat 索引等）
CREATE EXTENSION IF NOT EXISTS vector;

-- =====================================================
-- 用户表
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name     VARCHAR(50)  NOT NULL,
    user_phone    VARCHAR(20)  UNIQUE,
    user_email    VARCHAR(100) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    login_type    VARCHAR(20)  NOT NULL DEFAULT 'PASSWORD',
    nick_name     VARCHAR(100),
    user_avatar   VARCHAR(255),
    user_gender   VARCHAR(10)  NOT NULL DEFAULT 'OTHER',
    birthday      DATE,
    status        SMALLINT     NOT NULL DEFAULT 1,
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ,

    CONSTRAINT uk_cz_user_user_name UNIQUE (user_name),
    CONSTRAINT chk_cz_user_gender CHECK (user_gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT chk_cz_user_status CHECK (status IN (0, 1))
);

COMMENT ON TABLE cz_user IS '用户账号表';
COMMENT ON COLUMN cz_user.id IS '用户ID（初始化脚本使用 identity）';
COMMENT ON COLUMN cz_user.user_name IS '用户名（唯一）';
COMMENT ON COLUMN cz_user.user_phone IS '手机号（唯一，可空）';
COMMENT ON COLUMN cz_user.user_email IS '邮箱（唯一，可空）';
COMMENT ON COLUMN cz_user.password_hash IS '密码哈希（如 bcrypt）';
COMMENT ON COLUMN cz_user.login_type IS '注册/登录来源：PASSWORD/EMAIL_CODE/WECHAT/...';
COMMENT ON COLUMN cz_user.nick_name IS '昵称';
COMMENT ON COLUMN cz_user.user_avatar IS '头像URL';
COMMENT ON COLUMN cz_user.user_gender IS '性别：MALE/FEMALE/OTHER';
COMMENT ON COLUMN cz_user.birthday IS '生日';
COMMENT ON COLUMN cz_user.status IS '状态：1启用，0禁用';
COMMENT ON COLUMN cz_user.last_login_at IS '最近一次登录时间';
COMMENT ON COLUMN cz_user.created_at IS '创建时间';
COMMENT ON COLUMN cz_user.updated_at IS '更新时间';
COMMENT ON COLUMN cz_user.deleted_at IS '软删除时间（非空表示已删除）';

CREATE INDEX IF NOT EXISTS idx_cz_user_email ON cz_user(user_email);
CREATE INDEX IF NOT EXISTS idx_cz_user_phone ON cz_user(user_phone);

-- =====================================================
-- 学习资料表
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_resource
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    title         VARCHAR(200) NOT NULL,
    description   TEXT,
    file_name     VARCHAR(255),
    file_type     VARCHAR(50),
    file_path     VARCHAR(500),
    parse_status  SMALLINT     NOT NULL DEFAULT 0,
    vector_status SMALLINT     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_cz_resource_user FOREIGN KEY (user_id) REFERENCES cz_user(id)
);

COMMENT ON TABLE cz_resource IS '学习资料表（文档/网页/笔记等）';
COMMENT ON COLUMN cz_resource.id IS '资料ID';
COMMENT ON COLUMN cz_resource.user_id IS '所属用户ID';
COMMENT ON COLUMN cz_resource.title IS '标题';
COMMENT ON COLUMN cz_resource.description IS '描述/摘要（可空）';
COMMENT ON COLUMN cz_resource.file_name IS '原始文件名（可空）';
COMMENT ON COLUMN cz_resource.file_type IS '文件类型/扩展名（可空）';
COMMENT ON COLUMN cz_resource.file_path IS '存储路径或对象存储key（可空）';
COMMENT ON COLUMN cz_resource.parse_status IS '解析状态：0待解析，1成功，2失败（可扩展）';
COMMENT ON COLUMN cz_resource.vector_status IS '向量化状态：0待向量化，1成功，2失败（可扩展）';
COMMENT ON COLUMN cz_resource.created_at IS '创建时间';
COMMENT ON COLUMN cz_resource.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_cz_resource_user_id ON cz_resource(user_id);
CREATE INDEX IF NOT EXISTS idx_cz_resource_created_at ON cz_resource(created_at DESC);

-- =====================================================
-- 文本切块（资料的唯一数据源）
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_resource_chunk
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT      NOT NULL,
    chunk_no    INT         NOT NULL,
    content     TEXT        NOT NULL,
    token_count INT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cz_resource_chunk_resource
        FOREIGN KEY (resource_id) REFERENCES cz_resource(id) ON DELETE CASCADE,
    CONSTRAINT uk_cz_resource_chunk_no UNIQUE (resource_id, chunk_no)
);

COMMENT ON TABLE cz_resource_chunk IS '资料文本切块表（用于检索/向量化）';
COMMENT ON COLUMN cz_resource_chunk.id IS '切块ID';
COMMENT ON COLUMN cz_resource_chunk.resource_id IS '资料ID';
COMMENT ON COLUMN cz_resource_chunk.chunk_no IS '切块序号（同一资料内唯一）';
COMMENT ON COLUMN cz_resource_chunk.content IS '切块内容';
COMMENT ON COLUMN cz_resource_chunk.token_count IS 'token 数（可空）';
COMMENT ON COLUMN cz_resource_chunk.created_at IS '创建时间';

CREATE INDEX IF NOT EXISTS idx_cz_resource_chunk_resource_id ON cz_resource_chunk(resource_id);

-- =====================================================
-- AI 会话（元信息）
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_agent_session_meta
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL,
    session_name      VARCHAR(100),
    conversation_type VARCHAR(30) NOT NULL DEFAULT 'LEARNING_QA',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cz_agent_session_user FOREIGN KEY (user_id) REFERENCES cz_user(id)
);

COMMENT ON TABLE cz_agent_session_meta IS 'AI 会话表（会话元数据）';
COMMENT ON COLUMN cz_agent_session_meta.id IS '会话ID';
COMMENT ON COLUMN cz_agent_session_meta.user_id IS '所属用户ID';
COMMENT ON COLUMN cz_agent_session_meta.session_name IS '会话名称（可空）';
COMMENT ON COLUMN cz_agent_session_meta.conversation_type IS '会话类型（如 LEARNING_QA 等）';
COMMENT ON COLUMN cz_agent_session_meta.created_at IS '创建时间';
COMMENT ON COLUMN cz_agent_session_meta.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_cz_agent_session_user_id ON cz_agent_session_meta(user_id);
CREATE INDEX IF NOT EXISTS idx_cz_agent_session_created_at ON cz_agent_session_meta(created_at DESC);

-- =====================================================
-- AI 消息
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_ai_message
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT      NOT NULL,
    role         VARCHAR(20) NOT NULL,
    content      TEXT,
    model_name   VARCHAR(50),
    total_tokens INT,
    latency_ms   INT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cz_ai_message_session
        FOREIGN KEY (session_id) REFERENCES cz_agent_session_meta(id) ON DELETE CASCADE,
    CONSTRAINT chk_cz_ai_message_role CHECK (role IN ('system', 'user', 'assistant', 'tool'))
);

COMMENT ON TABLE cz_ai_message IS 'AI 消息表（会话内消息）';
COMMENT ON COLUMN cz_ai_message.id IS '消息ID';
COMMENT ON COLUMN cz_ai_message.session_id IS '会话ID';
COMMENT ON COLUMN cz_ai_message.role IS '角色：system/user/assistant/tool';
COMMENT ON COLUMN cz_ai_message.content IS '消息内容';
COMMENT ON COLUMN cz_ai_message.model_name IS '模型名称（可空）';
COMMENT ON COLUMN cz_ai_message.total_tokens IS 'token 数（可空）';
COMMENT ON COLUMN cz_ai_message.latency_ms IS '延迟（毫秒，可空）';
COMMENT ON COLUMN cz_ai_message.created_at IS '创建时间';

CREATE INDEX IF NOT EXISTS idx_cz_ai_message_session_id ON cz_ai_message(session_id);
CREATE INDEX IF NOT EXISTS idx_cz_ai_message_created_at ON cz_ai_message(created_at DESC);

-- =====================================================
-- 向量表（切块 embedding）
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_ai_embedding
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id   BIGINT      NOT NULL,
    embedding  vector(1536),
    model_name VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cz_ai_embedding_chunk
        FOREIGN KEY (chunk_id) REFERENCES cz_resource_chunk(id) ON DELETE CASCADE
);

COMMENT ON TABLE cz_ai_embedding IS '向量表（切块 embedding）';
COMMENT ON COLUMN cz_ai_embedding.id IS '向量ID';
COMMENT ON COLUMN cz_ai_embedding.chunk_id IS '切块ID';
COMMENT ON COLUMN cz_ai_embedding.embedding IS '向量（默认1536维）';
COMMENT ON COLUMN cz_ai_embedding.model_name IS 'embedding 模型名称（可空）';
COMMENT ON COLUMN cz_ai_embedding.created_at IS '创建时间';

-- 同一 chunk 默认只保留一条 embedding（若需要多模型共存可调整为 (chunk_id, model_name) 唯一）
CREATE UNIQUE INDEX IF NOT EXISTS uk_cz_ai_embedding_chunk_id ON cz_ai_embedding(chunk_id);

-- HNSW 索引（余弦距离）
CREATE INDEX IF NOT EXISTS idx_cz_ai_embedding_vector_hnsw
    ON cz_ai_embedding USING hnsw (embedding vector_cosine_ops);

-- =====================================================
-- RAG 检索日志
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_ai_retrieval_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    message_id BIGINT,
    query      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cz_ai_retrieval_log_session
        FOREIGN KEY (session_id) REFERENCES cz_agent_session_meta(id) ON DELETE SET NULL,
    CONSTRAINT fk_cz_ai_retrieval_log_message
        FOREIGN KEY (message_id) REFERENCES cz_ai_message(id) ON DELETE SET NULL
);

COMMENT ON TABLE cz_ai_retrieval_log IS 'RAG 检索日志表（每次检索的 query 等信息）';
COMMENT ON COLUMN cz_ai_retrieval_log.id IS '检索ID';
COMMENT ON COLUMN cz_ai_retrieval_log.session_id IS '会话ID（可空）';
COMMENT ON COLUMN cz_ai_retrieval_log.message_id IS '关联消息ID（可空）';
COMMENT ON COLUMN cz_ai_retrieval_log.query IS '检索 query 文本';
COMMENT ON COLUMN cz_ai_retrieval_log.created_at IS '创建时间';

CREATE INDEX IF NOT EXISTS idx_cz_ai_retrieval_log_session_id ON cz_ai_retrieval_log(session_id);
CREATE INDEX IF NOT EXISTS idx_cz_ai_retrieval_log_created_at ON cz_ai_retrieval_log(created_at DESC);

-- =====================================================
-- 检索结果明细
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_ai_retrieval_item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retrieval_id BIGINT NOT NULL,
    chunk_id     BIGINT NOT NULL,
    score        DOUBLE PRECISION,

    CONSTRAINT fk_cz_ai_retrieval_item_retrieval
        FOREIGN KEY (retrieval_id) REFERENCES cz_ai_retrieval_log(id) ON DELETE CASCADE,
    CONSTRAINT fk_cz_ai_retrieval_item_chunk
        FOREIGN KEY (chunk_id) REFERENCES cz_resource_chunk(id) ON DELETE CASCADE
);

COMMENT ON TABLE cz_ai_retrieval_item IS '检索结果明细表（召回的 chunk 与 score）';
COMMENT ON COLUMN cz_ai_retrieval_item.id IS '明细ID';
COMMENT ON COLUMN cz_ai_retrieval_item.retrieval_id IS '检索ID';
COMMENT ON COLUMN cz_ai_retrieval_item.chunk_id IS '切块ID';
COMMENT ON COLUMN cz_ai_retrieval_item.score IS '相似度/得分（值域由算法决定）';

CREATE INDEX IF NOT EXISTS idx_cz_ai_retrieval_item_retrieval_id ON cz_ai_retrieval_item(retrieval_id);
CREATE INDEX IF NOT EXISTS idx_cz_ai_retrieval_item_chunk_id ON cz_ai_retrieval_item(chunk_id);

-- =====================================================
-- 知识点（可选：从资料中抽取的结构化知识）
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_resource_knowledge
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT,
    title       VARCHAR(200),
    summary     TEXT,
    embedding   vector(1536),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cz_resource_knowledge_resource
        FOREIGN KEY (resource_id) REFERENCES cz_resource(id) ON DELETE CASCADE
);

COMMENT ON TABLE cz_resource_knowledge IS '知识点表（从资料抽取，可用于检索/复习）';
COMMENT ON COLUMN cz_resource_knowledge.id IS '知识点ID';
COMMENT ON COLUMN cz_resource_knowledge.resource_id IS '资料ID（可空）';
COMMENT ON COLUMN cz_resource_knowledge.title IS '知识点标题（可空）';
COMMENT ON COLUMN cz_resource_knowledge.summary IS '知识点摘要（可空）';
COMMENT ON COLUMN cz_resource_knowledge.embedding IS '知识点向量（可空）';
COMMENT ON COLUMN cz_resource_knowledge.created_at IS '创建时间';

CREATE INDEX IF NOT EXISTS idx_cz_resource_knowledge_resource_id ON cz_resource_knowledge(resource_id);

-- =====================================================
-- 学习计划
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_study_plan
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    title      VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_cz_study_plan_user FOREIGN KEY (user_id) REFERENCES cz_user(id)
);

COMMENT ON TABLE cz_study_plan IS '学习计划表';
COMMENT ON COLUMN cz_study_plan.id IS '计划ID';
COMMENT ON COLUMN cz_study_plan.user_id IS '所属用户ID';
COMMENT ON COLUMN cz_study_plan.title IS '计划标题';
COMMENT ON COLUMN cz_study_plan.created_at IS '创建时间';
COMMENT ON COLUMN cz_study_plan.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_cz_study_plan_user_id ON cz_study_plan(user_id);

-- =====================================================
-- 学习任务
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_study_task
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id    BIGINT      NOT NULL,
    content    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cz_study_task_plan FOREIGN KEY (plan_id) REFERENCES cz_study_plan(id) ON DELETE CASCADE
);

COMMENT ON TABLE cz_study_task IS '学习任务表';
COMMENT ON COLUMN cz_study_task.id IS '任务ID';
COMMENT ON COLUMN cz_study_task.plan_id IS '计划ID';
COMMENT ON COLUMN cz_study_task.content IS '任务内容';
COMMENT ON COLUMN cz_study_task.created_at IS '创建时间';
COMMENT ON COLUMN cz_study_task.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_cz_study_task_plan_id ON cz_study_task(plan_id);

-- =====================================================
-- 错题
-- =====================================================
CREATE TABLE IF NOT EXISTS cz_wrong_question
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id        BIGINT      NOT NULL,
    question       TEXT        NOT NULL,
    correct_answer TEXT,
    user_answer    TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cz_wrong_question_task FOREIGN KEY (task_id) REFERENCES cz_study_task(id) ON DELETE CASCADE
);

COMMENT ON TABLE cz_wrong_question IS '错题表';
COMMENT ON COLUMN cz_wrong_question.id IS '错题ID';
COMMENT ON COLUMN cz_wrong_question.task_id IS '所属任务ID';
COMMENT ON COLUMN cz_wrong_question.question IS '题目';
COMMENT ON COLUMN cz_wrong_question.correct_answer IS '正确答案（可空）';
COMMENT ON COLUMN cz_wrong_question.user_answer IS '用户答案（可空）';
COMMENT ON COLUMN cz_wrong_question.created_at IS '创建时间';

CREATE INDEX IF NOT EXISTS idx_cz_wrong_question_task_id ON cz_wrong_question(task_id);

