-- AI 会话消息表
CREATE TABLE cz_ai_message
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT NOT NULL,
    role        VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content     TEXT NOT NULL,
    token_count INT CHECK (token_count >= 0),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT cz_ai_message_role_check CHECK (role IN ('user', 'assistant', 'system'))
);

-- 添加索引
CREATE INDEX idx_cz_ai_message_session_id ON cz_ai_message(session_id);
CREATE INDEX idx_cz_ai_message_created_at ON cz_ai_message(created_at);

-- 添加注释
COMMENT ON TABLE cz_ai_message IS 'AI会话消息表';
COMMENT ON COLUMN cz_ai_message.id IS '主键ID';
COMMENT ON COLUMN cz_ai_message.session_id IS '会话ID';
COMMENT ON COLUMN cz_ai_message.role IS '角色: user用户/assistant助手/system系统';
COMMENT ON COLUMN cz_ai_message.content IS '消息内容';
COMMENT ON COLUMN cz_ai_message.token_count IS 'Token数量';
COMMENT ON COLUMN cz_ai_message.created_at IS '创建时间';

-- 向量表
CREATE EXTENSION vector;

CREATE TABLE cz_ai_embedding
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT NOT NULL,
    content     TEXT NOT NULL,
    embedding   vector(1536),
    metadata    JSONB DEFAULT '{}'::jsonb,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 添加索引
CREATE INDEX idx_cz_ai_embedding_resource_id ON cz_ai_embedding(resource_id);
CREATE INDEX idx_cz_ai_embedding_created_at ON cz_ai_embedding(created_at);
CREATE INDEX idx_cz_ai_embedding_embedding ON cz_ai_embedding USING ivfflat (embedding vector_cosine_ops);

-- 添加注释
COMMENT ON TABLE cz_ai_embedding IS 'AI向量表';
COMMENT ON COLUMN cz_ai_embedding.id IS '主键ID';
COMMENT ON COLUMN cz_ai_embedding.resource_id IS '资源ID';
COMMENT ON COLUMN cz_ai_embedding.content IS '原始内容';
COMMENT ON COLUMN cz_ai_embedding.embedding IS '向量数据(1536维)';
COMMENT ON COLUMN cz_ai_embedding.metadata IS '元数据(JSON格式)';
COMMENT ON COLUMN cz_ai_embedding.created_at IS '创建时间';

-- 知识块表
CREATE TABLE cz_ai_chunk
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT NOT NULL,
    chunk_index INT NOT NULL CHECK (chunk_index >= 0),
    content     TEXT NOT NULL,
    token_count INT CHECK (token_count >= 0),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT cz_ai_chunk_unique UNIQUE (resource_id, chunk_index)
);

-- 添加索引
CREATE INDEX idx_cz_ai_chunk_resource_id ON cz_ai_chunk(resource_id);
CREATE INDEX idx_cz_ai_chunk_resource_index ON cz_ai_chunk(resource_id, chunk_index);

-- 添加注释
COMMENT ON TABLE cz_ai_chunk IS 'AI知识块表';
COMMENT ON COLUMN cz_ai_chunk.id IS '主键ID';
COMMENT ON COLUMN cz_ai_chunk.resource_id IS '资源ID';
COMMENT ON COLUMN cz_ai_chunk.chunk_index IS '知识块索引';
COMMENT ON COLUMN cz_ai_chunk.content IS '知识块内容';
COMMENT ON COLUMN cz_ai_chunk.token_count IS 'Token数量';
COMMENT ON COLUMN cz_ai_chunk.created_at IS '创建时间';